site_name: Andy's Technical Notes
use_directory_urls: false
theme:
  name: material
  language: zh-TW
  font:
    text: Noto Serif TC
    text_weight: 400
    code: Roboto Mono
  custom_dir: docs/overrides
  icon:
    logo: material/server-network
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切換至深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切換至淺色模式
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
extra_css:
  - overrides/extra.css
nav:
  - 首頁: index.md
  - Dell CSM: csm/csm.md
  - GRAID: graid/graid.md
  - PVE: pve/pve.md
